app:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -p 3000
  ports:
    - "3000:3000"
  links:
    - db:postgres
  volumes:
    - "./:/app"
  environment:
    TWITTER_KEY: "${TWITTER_KEY}"
    TWITTER_SECRET: "${TWITTER_SECRET}"
    TWITTER_ACCESS_TOKEN: "${TWITTER_ACCESS_TOKEN}"
    TWITTER_ACCESS_SECRET: "${TWITTER_ACCESS_SECRET}"
    POSTGRES_USER: myapp
    POSTGRES_PASSWORD: password
    POSTMARK_API_TOKEN: "${POSTMARK_API_TOKEN}"

worker:
  build: .
  command: bundle exec rake jobs:work
  links:
    - db:postgres
  volumes:
    - "./:/app"
  environment:
    TWITTER_KEY: "${TWITTER_KEY}"
    TWITTER_SECRET: "${TWITTER_SECRET}"
    TWITTER_ACCESS_TOKEN: "${TWITTER_ACCESS_TOKEN}"
    TWITTER_ACCESS_SECRET: "${TWITTER_ACCESS_SECRET}"
    POSTGRES_USER: myapp
    POSTGRES_PASSWORD: password
    POSTMARK_API_TOKEN: "${POSTMARK_API_TOKEN}"

db:
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  volumes:
    - "database_volume:/var/lib/postgresql/data"
  environment:
    POSTGRES_USER: myapp
    POSTGRES_PASSWORD: password
